<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tools')->insert([
            ['name' => 'Penggorengan'],
            ['name' => 'Wajan'],
            ['name' => 'Pisau dapur'],
            ['name' => 'Cobek dan ulekan'],
            ['name' => 'Talenan'],
            ['name' => 'Spatula'],
            ['name' => 'Sendok sayur'],
            ['name' => 'Piring saji'],
            ['name' => 'Alat pengukur'],
            ['name' => 'Mangkuk besar'],
            ['name' => 'Panci'],
            ['name' => 'Sendok kayu'],
            ['name' => 'Piring'],
            ['name' => 'Mangkuk'],
            ['name' => 'Pengaduk'],
            ['name' => 'Garpu'],
            ['name' => 'Sendok atau spatula'],
            ['name' => 'Kertas roti atau loyang'],
            ['name' => 'Oven'],
            ['name' => 'Pengocok listrik atau mixer'],
            ['name' => 'Loyang kue'],
            ['name' => 'Pemotong kue berbentuk pohon Natal (opsional)'],
            ['name' => 'Mixer atau pengaduk elektrik'],
            ['name' => 'Loyang atau baking sheet'],
            ['name' => 'Sendok takar atau timbangan dapur'],
            ['name' => 'Loyang kue atau wadah penyimpanan'],
            ['name' => 'Kertas roti'],
            ['name' => 'Mangkok besar dan mangkok kecil'],
            ['name' => 'Kompor'],
            ['name' => 'Pisau'],
            ['name' => 'Sendok'],
            ['name' => 'Sendok besar'],
            ['name' => 'Peralatan untuk menumbuk (jika diperlukan)'],
            ['name' => 'Saringan (jika diperlukan)'],
            ['name' => 'Loyang atau wadah untuk membentuk adonan'],
            ['name' => 'Sendok kayu atau spatula'],
            ['name' => 'Wadah'],
            ['name' => 'Loyang atau loyang cetakan'],
            ['name' => 'Penggiling (opsional, terutama untuk menghaluskan bahan-bahan)'],
            ['name' => 'Panci kukus'],
            ['name' => 'Wadah untuk mencuci beras'],
            ['name' => 'Saringan atau wadah untuk merendam beras'],
            ['name' => 'Sendok pengaduk'],
            ['name' => 'Wajan (opsional, untuk menumis bumbu)'],
            ['name' => 'Mangkok'],
            ['name' => 'Tusuk sate'],
            ['name' => 'Blender atau penggiling bumbu'],
            ['name' => 'Pemanggang'],
            ['name' => 'Loyang'],
            ['name' => 'Blender atau alat penghalus lainnya'],
            ['name' => 'Wadah untuk mencampur adonan'],
            ['name' => 'Peralatan untuk mengukur suhu (opsional)'],
            ['name' => 'Sendok masak'],
            ['name' => 'Peralatan penggorengan (penggorengan dalam minyak)'],
            ['name' => 'Peralatan pencampur'],
            ['name' => 'Peralatan pengupas'],
            ['name' => 'Peralatan pengiris'],
            ['name' => 'Pisau potong'],
            ['name' => 'Saringan'],
            ['name' => 'Wadah tahan panas'],
            ['name' => 'Panci besar'],
            ['name' => 'Blender atau penghalus bumbu'],
            ['name' => 'Pemotong daging'],
            ['name' => 'Anyaman bambu'],
            ['name' => 'Pengaduk kayu'],
            ['name' => 'Kain bersih'],
            ['name' => 'Penggilingan atau blender'],
            ['name' => 'Mangkok besar'],
            ['name' => 'Loyang atau loyang roti'],
            ['name' => 'Kain serbet atau lap dapur'],
            ['name' => 'Pengaduk atau mixer'],
            ['name' => 'Gilingan atau rolling pin'],
            ['name' => 'Pengukur atau timbangan dapur'],
            ['name' => 'Kertas roti (parchment paper)'],
            ['name' => 'Kuali'],
            ['name' => 'Penyaring'],
            ['name' => 'Loyang atau wadah panggang'],
            ['name' => 'Gunting dapur'],
            ['name' => 'Gelas pengukur'],
            ['name' => 'Penggulung adonan (jika diperlukan)'],
            ['name' => 'Kuas pastry (jika diperlukan)'],
            ['name' => 'Kertas roti (jika diperlukan)'],
            ['name' => 'Pengocok telur'],
            ['name' => 'Loyang kue atau wadah kue'],
            ['name' => 'Sendok pengukur'],
            ['name' => 'Panci atau pengukus'],
            ['name' => 'Kain serbet atau kertas roti'],
            ['name' => 'Penggiling bumbu (opsional)'],
            ['name' => 'Pemotong kue (opsional)'],
            ['name' => 'Loyang atau cetakan kue bulat'],
            ['name' => 'Pengukur bahan'],
            ['name' => 'Penggulung kue (opsional)'],
            ['name' => 'Loyang baking'],
            ['name' => 'Mixer atau wisk'],
            ['name' => 'Sendok takar'],
            ['name' => 'Parutan keju'],
            ['name' => 'Talenan dan pisau untuk memotong kue'],
            ['name' => 'Gelas ukur'],
            ['name' => 'Es Batu Crusher'],
            ['name' => 'Pemanggang (opsional)'],
            ['name' => 'Saringan (opsional)'],
            ['name' => 'Pengocok es'],
            ['name' => 'Gergaji pisau (opsional untuk memotong es)'],
            ['name' => 'Ember (opsional untuk membuat es serut)'],
            ['name' => 'Kain Saring'],
            ['name' => 'Kukusan'],
            ['name' => 'Peralatan untuk memarut/remas rempah-rempah'],
            ['name' => 'Pengupas bawang dan bumbu lainnya'],
            ['name' => 'Gelas'],
            ['name' => 'Teko atau panci kecil'],
            ['name' => 'Penggorengan atau Panggangan'],
            ['name' => 'Peralatan Pengukur (sendok, gelas ukur)'],
            ['name' => 'Loyang atau wadah penyajian'],
            ['name' => 'Penghalus Bumbu (Blender atau Ulekan)'],
            ['name' => 'Penggiling atau blender (jika menggunakan bumbu halus)'],
            ['name' => 'Sendok makan'],
        ]);
    }
}
